### ISSUE TITLE
second tracker not discovered when adding 2 vehicles of the same year/make/model

### ISSUE THREAD

**Issue by metheos** [BigThunderSR/homeassistant-addons-onstar2mqtt#524]
I added my wife's vehicle today (using the vehicle 2 addon) after figuring everything out on mine and discovered that the tracker was not added for it. Looks like the info sent to MQTT would create a tracker with the same name and HA won't allow this.

```
Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:766
integration: Device tracker (documentation, issues)
First occurred: 12:36:29 PM (1 occurrences)
Last logged: 12:36:29 PM

Platform mqtt does not generate unique IDs. ID 2024_chevrolet_blazer_ev_device_tracker already exists - ignoring device_tracker.2024_chevrolet_blazer_ev
```

I didn't see a way to modify how the automatic discovery would name the tracker, so I just manually defined them in my configuration.yaml to work around this issue.

```
device_tracker:
  - platform: mqtt_json
    devices:
      wife_blazer_onstar: homeassistant/device_tracker/<VIN1>/getlocation/state
      my_blazer_onstar: homeassistant/device_tracker/<VIN2>/getlocation/state
```

Everything else seems to be working fine with both vehicles!
