### ISSUE TITLE
Suggested Fix for device tracker location

### ISSUE THREAD

**Issue by Audreth** [BigThunderSR/homeassistant-addons-onstar2mqtt#75]
### Solved the device tracker issue:

Taking the information from [HA-MQTT.md](https://github.com/BigThunderSR/onstar2mqtt/blob/main/HA-MQTT.md), I used the [script to get the car's location (Car - Location)](https://github.com/michaelwoods/onstar2mqtt/blob/main/HA-MQTT.md#script-yaml) as well as the [Automation](https://github.com/michaelwoods/onstar2mqtt/blob/main/HA-MQTT.md#automation) that went with it. 

I added the below code to my configuration.yaml and was able to get the location set properly for home, away (not_home), as well as other zones configured in home assistant

#### configuration.yaml
```yaml
mqtt:
  device_tracker:
  - name: "Location"
    state_topic: "homeassistant/device_tracker/ONSTAR_VIN/getlocation/state"
    value_template: "{% set ns = namespace(loc=[]) %}{% if (distance(value_json.latitude | float, value_json.longitude | float)*1000) <= state_attr('zone.home','radius') %}{% set ns.loc = ns.loc + [ 'home' ] %}{% else %}{% for zone in states.zone %}{% if distance(value_json.latitude | float, value_json.longitude | float, zone) * 1000 <= state_attr(zone.entity_id,'radius') %}{% set ns.loc = ns.loc + [ zone.name ] %}{% break %}{% endif %}{% endfor %}{% endif %}{% if ns.loc | length > 0 %}{{- ns.loc[0] }}{%else%}not_home{% endif %}"
    json_attributes_topic: "homeassistant/device_tracker/ONSTAR_VIN/getlocation/state"
    json_attributes_template: "{{ {'latitude': value_json.latitude | float, 'longitude': value_json.longitude | float } |tojson }}"
    device:
      identifiers:
      - ONSTAR_VIN
      manufacturer: *****
      model: '****'
      name: *****
    unique_id: ONSTAR_VIN-location
    source_type: gps
    payload_home: "home"
    payload_not_home: "not_home"
```
